#!/bin/sh

echo YADM is bootstrapping...

# Create symlinks to shell runcoms in $HOME.
bootstrap_xsh {
  print -P "%F{blue}::%f Linking shell runcoms to xsh runcoms..."

  # Source xsh with the appropriate configuration directory.
  XSH_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/shell"
  source "${XSH_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/xsh}/xsh.sh"

  # Bootstrap xsh for all supported shells.
  xsh bootstrap -s posix:bash:zsh >/dev/null
}

bootstrap_xsh
